openapi: 3.0.0
info:
  title: CAMARA simSwap
  version: 1.0.0
servers:
  - url: https://mobileconnect.telekom.de
tags:
  - name: ATP
paths:
  /token:
    post:
      tags:
        - ATP
      summary: Token
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded; charset=ISO-8859-1
        - name: Authorization
          in: header
          schema:
            type: string
          description: base64(client_id:client_secret)
          example: 'Basic '
        - name: grant_type
          in: query
          schema:
            type: string
          example: client_credentials
        - name: scope
          in: query
          schema:
            type: string
          example: mc_atp
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 18 Feb 2022 13:16:57 GMT
            Content-Type:
              schema:
                type: string
                example: application/json;charset=UTF-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Cache-Control:
              schema:
                type: string
                example: no-store
            Pragma:
              schema:
                type: string
                example: no-cache
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                access_token: mkmaJ53--rCK1SBUIjxzavoJCcFbx3453dKmZr39A8k
                scope: mc_atp
                token_type: Bearer
                expires_in: '500'
  /openid/userinfo:
    post:
      tags:
        - ATP
      summary: User Info
      description: userinfo
      requestBody:
        content: {}
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: '*/*'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: Authorization
          in: header
          schema:
            type: string
          description: Authorization token from Token request (token client_credentials)
          example: Bearer 81edUBMJBXQaZA-tiUdammZ5v9149MTklvy6_i93F7c
        - name: User-ID-Type
          in: header
          schema:
            type: string
          example: msisdn
        - name: User-ID
          in: header
          schema:
            type: integer
          description: Test MSISDN
          example: '4915164818763'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 18 Feb 2022 13:20:20 GMT
            Content-Type:
              schema:
                type: string
                example: application/json;charset=UTF-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Pragma:
              schema:
                type: string
                example: no-cache
            Cache-Control:
              schema:
                type: string
                example: no-store
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: User Info - BOOLEAN
                  value:
                    simChange: 'false'
                    correlation_id: 3149eec1-fc29-4bf6-8097-ddfd4a06d3db
                example-1:
                  summary: User Info - DATE
                  value:
                    simChange: '2020-07-13'
                    correlation_id: 59c82672-107b-4019-b469-169bf955d8f1